### ISSUE TITLE
issues about loading tfrs files

### ISSUE THREAD

**Issue by st2yang** [ricsonc/grnn#2]
Hi Ricson,

When I try to run the command python main.py grnn_shapenet_train, I got the error message 

tensorflow.python.framework.errors_impl.NotFoundError: double_tfrs/0; No such file or directory

The error seems to be related to the problematic path. I already downloaded the Shapenet derived datasets and put them in the top level of the Github repository.

Andy idea why this happens?

Thanks,
Yang

**Comment by ricsonc** [comment]
Can you verify that the file `grnn/double_tfrs/0` exists? (where "grnn" is the directory containing the repository).

**Comment by st2yang** [comment]
I was putting the folder like grnn/all_tfrs/double_tfrs. After I change to put every subfolder in the top level, the issue was resolved. Thanks!
