### ISSUE TITLE
Assuming camera no translation when data contain translation?

### ISSUE THREAD

**Issue by zlai0** [ricsonc/grnn#7]
Hi there, thanks a lot for your work! 

I was looking at the data processing code and find that the camera position for GQN Room dataset (rooms_ring_camera) is not used despite the rendering camera could be positioned differently. And it seems that this is done for both GRNN and the baseline method. Am I understanding correctly? If so, did this cause any problem for you?

Code:
https://github.com/ricsonc/grnn/blob/9e52959fe3cb9563f52a7f0c2b5b2804d6ae27ac/gqn_inputs.py#L322-L333

**Comment by ricsonc** [comment]
Hi, thanks for your interest.

The rooms_ring_camera dataset places the camera at a fixed distance from the center of the room, and it is always facing the center of the room. Therefore, pitch and yaw are sufficient to uniquely identify the position of the camera.
